FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

RUN apk add --no-cache ca-certificates tzdata

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/mcp-helm /mcp-helm

ARG VERSION=dev
ARG COMMIT=none
ARG DATE=unknown
ARG SOURCE=https://github.com/kubedoll-heavy-industries/helm-mcp

LABEL org.opencontainers.image.title="mcp-helm" \
  org.opencontainers.image.description="MCP server for interacting with Helm repositories and charts" \
  org.opencontainers.image.licenses="MIT" \
  org.opencontainers.image.source=$SOURCE \
  org.opencontainers.image.version=$VERSION \
  org.opencontainers.image.revision=$COMMIT \
  org.opencontainers.image.created=$DATE \
  io.modelcontextprotocol.server.name="io.github.kubedoll-heavy-industries/helm-mcp"

EXPOSE      8012
USER        65532:65532
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD ["/mcp-helm", "healthcheck"]
ENTRYPOINT  [ "/mcp-helm" ]
CMD         [ "--listen=:8012", "--transport=http" ]
